version: '3.8'
services:

  db:
    container_name: db
    image: postgres:13.3-alpine
    volumes:
      - /var/lib/postgresql/data/
    networks:
    - djangonetwork
    env_file:
      - .env

  backend:
    image: kirsbrosnone/foodgram_backend:latest
    restart: always
    volumes:
      - backend_static_value:/app/static/
      - backend_media_value:/app/media/
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
    env_file:
      - .env

  frontend:
    image: kirsbrosnone/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - backend_static_value:/var/html/backend_static/
      - backend_media_value:/var/html/backend_media/
    depends_on:
      - frontend

networks:
  djangonetwork:
    driver: bridge

volumes:
  postgres_data:
  backend_static_value:
  backend_media_value:
