# Generated by Django 3.2.15 on 2022-08-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220815_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#D3D3D3', help_text='Цвет в формате HEX #D3D3D3', max_length=7, null=True, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Имя тэга', max_length=200, unique=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Уникальный слаг', max_length=200, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
