# Generated by Django 3.2.15 on 2022-08-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220816_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofingredient',
            name='ingredient_recipe',
            field=models.ForeignKey(help_text='Выберите ингридиент', on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
