# Generated by Django 3.2.15 on 2022-08-30 18:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_amountofingredient_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountofingredient',
            options={'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
        migrations.AlterField(
            model_name='amountofingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Минимальное количество ингредиента')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='amountofingredient',
            name='ingredient_recipe',
            field=models.ForeignKey(help_text='Выберите ингредиент', on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=10, help_text='В минутах', validators=[django.core.validators.MinValueValidator(1, 'Минимальное время приготовления 1 мин.')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#D3D3D3', help_text='Цвет в формате HEX например: #D3D3D3', max_length=7, unique=True, verbose_name='Цвет'),
        ),
    ]
